title: AngioPilot
description: "Scenario-Based Vascular Catheterization Simulation Training Tool"
url: "https://hunterh37.github.io"
baseurl: "/AngioPilotWebsite"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
